### ISSUE TITLE
[BUG] Terminal shows "Lyrics unavailable for  by ."

### ISSUE THREAD

**Issue by gaztum** [SwagLyrics/SwagLyrics-For-Spotify#2409] opened 2020-06-24 18:44 UTC
**Describe the bug**
Terminal shows "Lyrics unavailable for  by ." message when the destination source changes by the user (reproduce the song on another device)

**To Reproduce**
1. Open spotify
2. Play any song
3. Change destination device

**Expected behavior**
Shows lyrics because the spotify still open on my laptop

**Screenshots**
Spotify
![image](https://user-images.githubusercontent.com/61505273/85614339-2c3bf100-b631-11ea-99f8-60b90208d16c.png)

Terminal
![image](https://user-images.githubusercontent.com/61505273/85613701-86888200-b630-11ea-8a10-5425c5069345.png)

**Desktop (please complete the following information):**
 - OS: UBUNTU
 - Version 20.04

**Comment by aadibajpai** [comment] 2020-06-25 06:26
The thing is, that when the Spotify is not actually playing the song on your device it stops communicating that info to the device and hence by extension, to SwagLyrics. 

I don't think there is a direct fix, but I can offer you a way to get the lyrics even when you're playing Spotify on a different device.
If you use the Spotify Web Player on Chrome with the [SwagLyrics Chrome Extension](https://chrome.google.com/webstore/detail/swaglyrics-for-spotify/miopldoofdhmipepmnclnoangcdffmlk), then it will be compatible even when you're playing Spotify on a different device. 
If you're more of a Firefox person, we should have an extension for that really soon as well.
You can probably just have tab running and it should work.

Example:
![image](https://user-images.githubusercontent.com/27063113/85667035-c86e0280-b6da-11ea-8a11-3ce946025e94.png)

**Comment by aadibajpai** [comment] 2020-06-25 07:13
Sort of duplicate of https://github.com/SwagLyrics/SwSpotify/issues/11

**Closed** 2020-08-05 14:04 UTC
