### ISSUE TITLE
No support for Polish special characters

### ISSUE THREAD

**Issue by bartekpacia** [SwagLyrics/SwagLyrics-For-Spotify#2376] opened 2020-06-09 13:49 UTC
**Describe the bug**
Play [this song](https://open.spotify.com/track/77vLpSAMNzeYL4EBeZxWqI?si=Fm8AA8_6SgiU2St5g_B0ww) and try getting lyrics.

You'll get this `Getting lyrics for Ma?omiasteczkowy by Dawid Podsiad?o.`

**Expected behavior**
I should see `Getting lyrics for Małomiasteczkowy by Dawid Podsiadło.`

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.5 19F101 x86_64
 - Version: swaglyrics `1.2.0`

**Comment by aadibajpai** [comment] 2020-06-09 15:33
I don't seem to be able to reproduce this issue. 
![image](https://user-images.githubusercontent.com/27063113/84167944-78652e00-aa94-11ea-8d58-f2a6a7c3a543.png)
I feel this most likely is an issue with supported encodings in your terminal than that of swaglyrics.
Last GCI, someone encountered a similar issue with Japanese/Chinese characters and we added a small thing at the end of the usage section here https://github.com/SwagLyrics/SwagLyrics-For-Spotify#usage. I think that might help here, just in case.

**Comment by bartekpacia** [comment] 2020-06-09 18:45
Hmm, okay. Thanks for a quick response, I'll poke around with it.

BTW`chcp` command isn't found

**Comment by flabbet** [comment] 2020-06-10 07:43
Yup, I couldn't reproduce it either. Seems like an issue with your terminal encodings

**Comment by aadibajpai** [comment] 2020-06-10 07:58
> Hmm, okay. Thanks for a quick response, I'll poke around with it.
> 
> BTW `chcp` command isn't found at my machine

Yeah chcp looks like a Windows thing, I'm not sure what the macOS equivalent is.

**Comment by aadibajpai** [comment] 2020-06-18 21:24
@bartekpacia any luck? I had found this https://stackoverflow.com/questions/4606570/os-x-terminal-utf-8-issues, if it helps.

**Comment by bartekpacia** [comment] 2020-06-18 21:34
No luck, but it isn't anything particularly annoying. I can live with it.

Thank you for this link tho :) I use iTerm2 (not the default Terminal) and have UTF-8 set.

**Comment by aadibajpai** [comment] 2020-06-18 22:55
Very well, I shall close the issue since it's a user config issue. Btw you might want to join the [SwagLyrics Discord](https://discord.swaglyrics.dev) for faster support 😄

**Closed by aadibajpai** 2020-06-18 22:55 UTC
Labels: bug

**Comment by bartekpacia** [comment] 2020-06-18 23:29
Thanks, done:)
